=== LavenderSnek/ShimejiEE-cross-platform/ext-resources/conf/Mascot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.group-finity.com/Mascot" elementFormDefault="qualified"
        xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.group-finity.com/Mascot">

    <element name="Mascot" type="tns:Mascot"/>

    <complexType name="Mascot">
        <sequence>
            <element name="ActionList" type="tns:ActionList" maxOccurs="unbounded" minOccurs="0"/>
            <element name="BehaviorList" type="tns:BehaviorList" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="ActionList">
        <choice maxOccurs="unbounded" minOccurs="0">
            <element name="Action" type="tns:TopAction"/>
        </choice>
    </complexType>

    <complexType name="ActionArguments" abstract="true">
        <attribute name="Condition" type="tns:Parameter"/>
        <attribute name="Duration" type="tns:Parameter"/>
        <attribute name="TargetX" type="tns:Parameter"/>
        <attribute name="TargetY" type="tns:Parameter"/>
        <attribute name="InitialVX" type="tns:Parameter"/>
        <attribute name="InitialVY" type="tns:Parameter"/>
        <attribute name="X" type="tns:Parameter"/>
        <attribute name="Y" type="tns:Parameter"/>
        <attribute name="LookRight" type="tns:Parameter"/>
        <attribute name="IeOffsetX" type="tns:Parameter"/>
        <attribute name="IeOffsetY" type="tns:Parameter"/>
        <attribute name="Gap" type="tns:Parameter"/>
        <attribute name="BornX" type="tns:Parameter"/>
        <attribute name="BornY" type="tns:Parameter"/>
        <attribute name="BornBehavior"/>
        <attribute name="VelocityParam" type="tns:Parameter"/>
        <attribute name="RegistanceX" type="tns:Parameter"/>
        <attribute name="RegistanceY" type="tns:Parameter"/>
        <attribute name="Gravity" type="tns:Parameter"/>
    </complexType>

    <complexType name="Action">
        <complexContent>
            <extension base="tns:ActionArguments">
                <choice>
                    <element name="Animation" type="tns:Animation" maxOccurs="unbounded" minOccurs="0"/>
                    <sequence>
                        <choice maxOccurs="unbounded" minOccurs="0">
                            <element name="ActionReference" type="tns:ActionReference"/>
                            <element name="Action" type="tns:LowerAction"/>
                        </choice>
                    </sequence>
                </choice>
                <attribute name="Type" use="required">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Embedded"/>
                            <enumeration value="Move"/>
                            <enumeration value="Stay"/>
                            <enumeration value="Animate"/>
                            <enumeration value="Sequence"/>
                            <enumeration value="Select"/>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="Class">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="com.group_finity.mascot.action.Breed"/>
                            <enumeration value="com.group_finity.mascot.action.Broadcast"/>
                            <enumeration value="com.group_finity.mascot.action.BroadcastMove"/>
                            <enumeration value="com.group_finity.mascot.action.BroadcastStay"/>
                            <enumeration value="com.group_finity.mascot.action.Dragged"/>
                            <enumeration value="com.group_finity.mascot.action.Fall"/>
                            <enumeration value="com.group_finity.mascot.action.FallWithIE"/>
                            <enumeration value="com.group_finity.mascot.action.Interact"/>
                            <enumeration value="com.group_finity.mascot.action.Jump"/>
                            <enumeration value="com.group_finity.mascot.action.Look"/>
                            <enumeration value="com.group_finity.mascot.action.MoveWithTurn"/>
                            <enumeration value="com.group_finity.mascot.action.Mute"/>
                            <enumeration value="com.group_finity.mascot.action.Offset"/>
                            <enumeration value="com.group_finity.mascot.action.Regist"/>
                            <enumeration value="com.group_finity.mascot.action.ScanMove"/>
                            <enumeration value="com.group_finity.mascot.action.SelfDestruct"/>
                            <enumeration value="com.group_finity.mascot.action.ThrowIE"/>
                            <enumeration value="com.group_finity.mascot.action.Transform"/>
                            <enumeration value="com.group_finity.mascot.action.Turn"/>
                            <enumeration value="com.group_finity.mascot.action.WalkWithIE"/>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="BorderType">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Floor"/>
                            <enumeration value="Wall"/>
                            <enumeration value="Ceiling"/>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="Loop" type="tns:Parameter"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TopAction">
        <complexContent>
            <extension base="tns:Action">
                <attribute name="Name" type="string" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="LowerAction">
        <complexContent>
            <extension base="tns:Action"/>
        </complexContent>
    </complexType>

    <complexType name="Animation">
        <sequence>
            <element name="Pose" type="tns:Pose" maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
        <attribute name="Condition" type="string"/>
    </complexType>

    <complexType name="Pose">
        <attribute name="Image" use="required">
            <simpleType>
                <restriction base="string">
                    <pattern value="/.+\.(png|bmp|PNG|BMP)"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="ImageRight">
            <simpleType>
                <restriction base="string">
                    <pattern value="/.+\.(png|bmp|PNG|BMP)"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="ImageAnchor" use="required">
            <simpleType>
                <restriction base="string">
                    <pattern value="-?\d+,-?\d+"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="Velocity" use="required">
            <simpleType>
                <restriction base="string">
                    <pattern value="-?\d+,-?\d+"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="Duration" type="int" use="required"/>
        <!--    sound    -->
        <attribute name="Sound">
            <simpleType>
                <restriction base="string">
                    <pattern value="/.*"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="Volume" type="float" default="0"/>
    </complexType>

    <complexType name="ActionReference">
        <complexContent>
            <extension base="tns:ActionArguments">
                <attribute name="Name" type="string" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="BehaviorList">
        <sequence>
            <choice maxOccurs="unbounded" minOccurs="1">
                <element name="Behavior" type="tns:Behavior"/>
                <element name="Condition" type="tns:BehaviorCondition"/>
            </choice>
        </sequence>
    </complexType>

    <complexType name="Behavior">
        <sequence>
            <choice maxOccurs="1" minOccurs="0">
                <element name="NextBehaviorList" type="tns:NextBehaviorList"/>
            </choice>
        </sequence>
        <attribute name="Name" type="string" use="required"/>
        <attribute name="Frequency" type="int" use="required"/>
        <attribute name="Condition" type="tns:Parameter"/>
        <attribute name="Hidden" type="boolean"/>
    </complexType>

    <complexType name="NextBehaviorList">
        <sequence>
            <choice maxOccurs="unbounded" minOccurs="1">
                <element name="BehaviorReference" type="tns:BehaviorReference"/>
                <element name="Condition" type="tns:BehaviorReferenceCondition"/>
            </choice>
        </sequence>
        <attribute name="Add" type="boolean" use="required"/>
    </complexType>

    <complexType name="BehaviorReferenceCondition">
        <complexContent>
            <extension base="tns:NextBehaviorList">
                <attribute name="Condition" type="string"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="BehaviorReference">
        <attribute name="Name" type="string" use="required"/>
        <attribute name="Frequency" type="int" use="required"/>
        <attribute name="Condition" type="tns:Parameter"/>
    </complexType>

    <complexType name="BehaviorCondition">
        <complexContent>
            <extension base="tns:BehaviorList">
                <attribute name="Condition" type="tns:Parameter"/>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Parameter">
        <restriction base="string">
            <pattern value="([$#]\{.+\})|(-?[0-9]+(\.[0-9]+)?)|true|false"/>
        </restriction>
    </simpleType>

</schema>

=== LavenderSnek/ShimejiEE-cross-platform/ShimejiEE/conf/behaviors.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Mascot xmlns="http://www.group-finity.com/Mascot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.group-finity.com/Mascot Mascot.xsd">

	<BehaviorList>
	
		<!-- ALWAYS REQUIRED -->
		<Behavior Name="ChaseMouse" Frequency="0" Hidden="true">
			<NextBehaviorList Add="false">
				<BehaviorReference Name="SitAndFaceMouse" Frequency="1" />
			</NextBehaviorList>
		</Behavior>
		
		<Behavior Name="SitAndFaceMouse" Frequency="0">
			<NextBehaviorList Add="false">
				<BehaviorReference Name="SitAndFaceMouse" Frequency="100" />
				<BehaviorReference Name="SitAndSpinHead" Frequency="1" />
				<BehaviorReference Name="SitWhileDanglingLegs" Frequency="1" />
			</NextBehaviorList>
		</Behavior>
		
		<Behavior Name="SitAndSpinHead" Frequency="0">
			<NextBehaviorList Add="false">
				<BehaviorReference Name="SitAndFaceMouse" Frequency="1" />
			</NextBehaviorList>
		</Behavior>
		
		<!-- ALWAYS REQUIRED -->
		<Behavior Name="Fall" Frequency="0" Hidden="true" />
		
		<!-- ALWAYS REQUIRED -->
		<Behavior Name="Dragged" Frequency="0" Hidden="true" />
		
		<!-- ALWAYS REQUIRED -->
		<Behavior Name="Thrown" Frequency="0" Hidden="true" />
		
		<Behavior Name="PullUp" Frequency="0" Hidden="true" />
		<Behavior Name="Divided" Frequency="0" Hidden="true" />

		<!-- On the Floor -->
		<Condition Condition="#{mascot.environment.floor.isOn(mascot.anchor) || mascot.environment.activeIE.topBorder.isOn(mascot.anchor)}">
			<Behavior Name="StandUp" Frequency="200" Hidden="true" />
			<Behavior Name="SitDown" Frequency="200">
				<NextBehaviorList Add="true">
					<BehaviorReference Name="SitWhileDanglingLegs" Frequency="100" />
					<BehaviorReference Name="LieDown" Frequency="100" />
				</NextBehaviorList>
			</Behavior>
			<Behavior Name="SitWhileDanglingLegs" Frequency="0" />
			<Behavior Name="LieDown" Frequency="0">
				<NextBehaviorList Add="false">
					<BehaviorReference Name="SitDown" Frequency="100" />
					<BehaviorReference Name="CrawlAlongIECeiling" Frequency="100" Condition="${mascot.environment.activeIE.topBorder.isOn(mascot.anchor)}"/>
					<BehaviorReference Name="CrawlAlongWorkAreaFloor" Frequency="100" Condition="${mascot.environment.floor.isOn(mascot.anchor)}" />
				</NextBehaviorList>
			</Behavior>
			
			<Behavior Name="SplitIntoTwo" Frequency="50" Condition="#{mascot.totalCount &lt; 50}" />
		</Condition>

		<!-- On the Wall -->
		<Condition Condition="#{ mascot.lookRight ? (
					mascot.environment.workArea.rightBorder.isOn(mascot.anchor) || 
					mascot.environment.activeIE.leftBorder.isOn(mascot.anchor) ) : (
					mascot.environment.workArea.leftBorder.isOn(mascot.anchor) || 
					mascot.environment.activeIE.rightBorder.isOn(mascot.anchor) ) }">
			<Behavior Name="HoldOntoWall" Frequency="100" Hidden="true" />
			<Behavior Name="FallFromWall" Frequency="50" Condition="${!mascot.environment.floor.isOn(mascot.anchor)}" Hidden="true" />
		</Condition>
		
		<!-- On the Ceiling -->
		<Condition Condition="#{mascot.environment.ceiling.isOn(mascot.anchor) || mascot.environment.activeIE.bottomBorder.isOn(mascot.anchor)}">
			<Behavior Name="HoldOntoCeiling" Frequency="100" Hidden="true" />
			<Behavior Name="FallFromCeiling" Frequency="50" Hidden="true" />
		</Condition>
		
		<!-- On Work Area Floor -->
		<Condition Condition="#{mascot.environment.floor.isOn(mascot.anchor)}">
			<Behavior Name="WalkAlongWorkAreaFloor" Frequency="100" Hidden="true" />
			<Behavior Name="RunAlongWorkAreaFloor" Frequency="100" Hidden="true" />
			<Behavior Name="CrawlAlongWorkAreaFloor" Frequency="10">
				<NextBehaviorList Add="false">
					<!-- Finished Crawling -->
					<BehaviorReference Name="LieDown" Frequency="1" />
				</NextBehaviorList>
			</Behavior>
			<Behavior Name="WalkLeftAlongFloorAndSit" Frequency="100" Hidden="true" />
			<Behavior Name="WalkRightAlongFloorAndSit" Frequency="100" Hidden="true" />
			<Behavior Name="GrabWorkAreaBottomLeftWall" Frequency="100" Hidden="true" />
			<Behavior Name="GrabWorkAreaBottomRightWall" Frequency="100" Hidden="true" />
			<Behavior Name="WalkLeftAndSit" Frequency="100" Hidden="true" />
			<Behavior Name="WalkRightAndSit" Frequency="100" Hidden="true" />
			<Behavior Name="WalkAndGrabBottomLeftWall" Frequency="100" />
			<Behavior Name="WalkAndGrabBottomRightWall" Frequency="100" />
			<Behavior Name="JumpFromBottomOfIE" Frequency="50" Condition="#{mascot.anchor.x &gt;= mascot.environment.activeIE.left &amp;&amp;
				mascot.anchor.x &lt; mascot.environment.activeIE.right}" />
				
			<Behavior Name="PullUpShimeji" Frequency="50" Condition="#{mascot.totalCount &lt; 50}" />
		</Condition>
		
		<!-- On Work Area Facing the Wall -->
		<Condition Condition="#{mascot.lookRight ? mascot.environment.workArea.rightBorder.isOn(mascot.anchor) :
					mascot.environment.workArea.leftBorder.isOn(mascot.anchor)}">
			<Behavior Name="ClimbHalfwayAlongWall" Frequency="100" Hidden="true" />
			<Behavior Name="ClimbAlongWall" Frequency="100" />
		</Condition>
		
		<!-- On Work Area Top Facing -->
		<Condition Condition="#{mascot.environment.ceiling.isOn(mascot.anchor)}">
			<Behavior Name="ClimbAlongCeiling" Frequency="100" />
		</Condition>
		
		<!-- On Top of IE -->
		<Condition Condition="#{mascot.environment.activeIE.topBorder.isOn(mascot.anchor)}">
			<Behavior Name="WalkAlongIECeiling" Frequency="100" Hidden="true" />
			<Behavior Name="RunAlongIECeiling" Frequency="100" Hidden="true" />
			<Behavior Name="CrawlAlongIECeiling" Frequency="10" Hidden="true">
				<NextBehaviorList Add="false">
					<!-- Finished Crawling -->
					<BehaviorReference Name="LieDown" Frequency="1" />
				</NextBehaviorList>
			</Behavior>
			<Behavior Name="SitOnTheLeftEdgeOfIE" Frequency="100" Hidden="true" />
			<Behavior Name="SitOnTheRightEdgeOfIE" Frequency="100" Hidden="true" />
			<Behavior Name="JumpFromLeftEdgeOfIE" Frequency="100" Hidden="true" />
			<Behavior Name="JumpFromRightEdgeOfIE" Frequency="100" Hidden="true" />
			<Behavior Name="WalkLeftAlongIEAndSit" Frequency="100" Hidden="true" />
			<Behavior Name="WalkRightAlongIEAndSit" Frequency="100" Hidden="true" />
			<Behavior Name="WalkLeftAlongIEAndJump" Frequency="100" Hidden="true" />
			<Behavior Name="WalkRightAlongIEAndJump" Frequency="100" Hidden="true" />
		</Condition>
		
		<!-- On IE's Side -->
		<Condition Condition="#{mascot.lookRight ? mascot.environment.activeIE.leftBorder.isOn(mascot.anchor) :
					mascot.environment.activeIE.rightBorder.isOn(mascot.anchor)}">
			<Behavior Name="HoldOntoIEWall" Frequency="100" Hidden="true" />
			<Behavior Name="ClimbIEWall" Frequency="100" Hidden="true" />
			
		</Condition>

		<!-- On the Bottom of IE -->
		<Condition Condition="#{mascot.environment.activeIE.bottomBorder.isOn(mascot.anchor)}">
			<Behavior Name="ClimbIEBottom" Frequency="100" Hidden="true" />
			<Behavior Name="GrabIEBottomLeftWall" Frequency="100" Hidden="true" />
			<Behavior Name="GrabIEBottomRightWall" Frequency="100" Hidden="true" />
		</Condition>
		
		<Behavior Name="JumpFromLeftWall" Frequency="50" Condition="#{!mascot.environment.workArea.leftBorder.isOn(mascot.anchor) &amp;&amp;
			mascot.anchor.x &lt; mascot.environment.workArea.left+400 &amp;&amp;
			Math.abs(mascot.environment.workArea.bottom-mascot.anchor.y) &lt;mascot.environment.workArea.height/4}" Hidden="true" />
		<Behavior Name="JumpFromRightWall" Frequency="50" Condition="#{!mascot.environment.workArea.rightBorder.isOn(mascot.anchor) &amp;&amp;
			mascot.anchor.x &gt;= mascot.environment.workArea.right-400 &amp;&amp;
			Math.abs(mascot.environment.workArea.bottom-mascot.anchor.y) &lt;mascot.environment.workArea.height/4}" Hidden="true" />

		<!-- IE Is Visible -->
		<Condition Condition="#{mascot.environment.activeIE.visible}">
			<Behavior Name="JumpOnIELeftWall" Frequency="50" Condition="#{mascot.anchor.x &lt; mascot.environment.activeIE.left &amp;&amp;
				Math.abs(mascot.environment.activeIE.bottom-mascot.anchor.y) &lt;mascot.environment.activeIE.height/4}" Hidden="true" />
			<Behavior Name="JumpOnIERightWall" Frequency="50" Condition="#{mascot.anchor.x &gt; mascot.environment.activeIE.right &amp;&amp;
				Math.abs(mascot.environment.activeIE.bottom-mascot.anchor.y) &lt;mascot.environment.activeIE.height/4}" Hidden="true" />
				
			<Behavior Name="ThrowIEFromLeft" Frequency="20" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &lt; mascot.environment.activeIE.left}" />
			<Behavior Name="ThrowIEFromRight" Frequency="20" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &gt; mascot.environment.activeIE.right}" />
			<Behavior Name="WalkAndThrowIEFromRight" Frequency="20" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &lt; mascot.environment.activeIE.left}" />
			<Behavior Name="WalkAndThrowIEFromLeft" Frequency="20" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &gt; mascot.environment.activeIE.right}" />
		</Condition>

	</BehaviorList>
</Mascot>

=== LavenderSnek/ShimejiEE-cross-platform/ShimejiEE/conf/CalmBehavior.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Mascot xmlns="http://www.group-finity.com/Mascot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.group-finity.com/Mascot Mascot.xsd">

	<BehaviorList>

		<!-- ALWAYS REQUIRED -->
		<Behavior Name="ChaseMouse" Frequency="0">
			<NextBehaviorList Add="false">
				<BehaviorReference Name="SitAndFaceMouse" Frequency="1" />
			</NextBehaviorList>
		</Behavior>

		<Behavior Name="SitAndFaceMouse" Frequency="0">
			<NextBehaviorList Add="false">
				<BehaviorReference Name="SitAndFaceMouse" Frequency="100" />
				<BehaviorReference Name="SitAndSpinHead" Frequency="1" />
				<BehaviorReference Name="SitWhileDanglingLegs" Frequency="1" />
			</NextBehaviorList>
		</Behavior>

		<Behavior Name="SitAndSpinHead" Frequency="0">
			<NextBehaviorList Add="false">
				<BehaviorReference Name="SitAndFaceMouse" Frequency="1" />
			</NextBehaviorList>
		</Behavior>

		<!-- ALWAYS REQUIRED -->
		<Behavior Name="Fall" Frequency="0" />

		<!-- ALWAYS REQUIRED -->
		<Behavior Name="Dragged" Frequency="0" />

		<!-- ALWAYS REQUIRED -->
		<Behavior Name="Thrown" Frequency="0" />

		<Behavior Name="PullUp" Frequency="0" />
		<Behavior Name="Divided" Frequency="0" />

		<!-- On the Floor -->
		<Condition Condition="#{mascot.environment.floor.isOn(mascot.anchor) || mascot.environment.activeIE.topBorder.isOn(mascot.anchor)}">
			<Behavior Name="StandUp" Frequency="200" />
			<Behavior Name="SitDown" Frequency="100">
				<NextBehaviorList Add="true">
					<BehaviorReference Name="SitWhileDanglingLegs" Frequency="100" />
					<BehaviorReference Name="LieDown" Frequency="100" />
				</NextBehaviorList>
			</Behavior>
			<Behavior Name="SitWhileDanglingLegs" Frequency="0" />
			<Behavior Name="LieDown" Frequency="0">
				<NextBehaviorList Add="false">
					<BehaviorReference Name="SitDown" Frequency="100" />
					<BehaviorReference Name="CrawlAlongIECeiling" Frequency="100" Condition="${mascot.environment.activeIE.topBorder.isOn(mascot.anchor)}" />
					<BehaviorReference Name="CrawlAlongWorkAreaFloor" Frequency="100" Condition="${mascot.environment.floor.isOn(mascot.anchor)}" />
				</NextBehaviorList>
			</Behavior>

			<Behavior Name="SplitIntoTwo" Frequency="0" Condition="#{mascot.totalCount &lt; 10}" />
		</Condition>

		<!-- On the Wall -->
		<Condition Condition="#{ mascot.lookRight ? (
					mascot.environment.workArea.rightBorder.isOn(mascot.anchor) ||
					mascot.environment.activeIE.leftBorder.isOn(mascot.anchor) ) : (
					mascot.environment.workArea.leftBorder.isOn(mascot.anchor) ||
					mascot.environment.activeIE.rightBorder.isOn(mascot.anchor) ) }">
			<Behavior Name="HoldOntoWall" Frequency="100" />
			<Behavior Name="FallFromWall" Frequency="100" Condition="${!mascot.environment.floor.isOn(mascot.anchor)}" />
		</Condition>

		<!-- On the Ceiling -->
		<Condition Condition="#{mascot.environment.ceiling.isOn(mascot.anchor) || mascot.environment.activeIE.bottomBorder.isOn(mascot.anchor)}">
			<Behavior Name="HoldOntoCeiling" Frequency="100" />
			<Behavior Name="FallFromCeiling" Frequency="0" />
		</Condition>

		<!-- On Work Area Floor -->
		<Condition Condition="#{mascot.environment.floor.isOn(mascot.anchor)}">
			<Behavior Name="WalkAlongWorkAreaFloor" Frequency="200" />
			<Behavior Name="RunAlongWorkAreaFloor" Frequency="0" />
			<Behavior Name="CrawlAlongWorkAreaFloor" Frequency="10">
				<NextBehaviorList Add="false">
					<!-- Finished Crawling -->
					<BehaviorReference Name="LieDown" Frequency="1" />
				</NextBehaviorList>
			</Behavior>
			<Behavior Name="WalkLeftAlongFloorAndSit" Frequency="60" />
			<Behavior Name="WalkRightAlongFloorAndSit" Frequency="60" />
			<Behavior Name="GrabWorkAreaBottomLeftWall" Frequency="0" />
			<Behavior Name="GrabWorkAreaBottomRightWall" Frequency="0" />
			<Behavior Name="WalkLeftAndSit" Frequency="0" />
			<Behavior Name="WalkRightAndSit" Frequency="0" />
			<Behavior Name="WalkAndGrabBottomLeftWall" Frequency="0" />
			<Behavior Name="WalkAndGrabBottomRightWall" Frequency="0" />
			<Behavior Name="JumpFromBottomOfIE" Frequency="0" Condition="#{mascot.anchor.x &gt;= mascot.environment.activeIE.left &amp;&amp;
				mascot.anchor.x &lt; mascot.environment.activeIE.right}" />

			<Behavior Name="PullUpShimeji" Frequency="0" Condition="#{mascot.totalCount &lt; 10}" />
		</Condition>

		<!-- On Work Area Facing the Wall -->
		<Condition Condition="#{mascot.lookRight ? mascot.environment.workArea.rightBorder.isOn(mascot.anchor) :
					mascot.environment.workArea.leftBorder.isOn(mascot.anchor)}">
			<Behavior Name="ClimbHalfwayAlongWall" Frequency="100" />
			<Behavior Name="ClimbAlongWall" Frequency="0" />
		</Condition>

		<!-- On Work Area Top Facing -->
		<Condition Condition="#{mascot.environment.ceiling.isOn(mascot.anchor)}">
			<Behavior Name="ClimbAlongCeiling" Frequency="100" />
		</Condition>

		<!-- On Top of IE -->
		<Condition Condition="#{mascot.environment.activeIE.topBorder.isOn(mascot.anchor)}">
			<Behavior Name="WalkAlongIECeiling" Frequency="200" />
			<Behavior Name="RunAlongIECeiling" Frequency="100" />
			<Behavior Name="CrawlAlongIECeiling" Frequency="10">
				<NextBehaviorList Add="false">
					<!-- Finished Crawling -->
					<BehaviorReference Name="LieDown" Frequency="1" />
				</NextBehaviorList>
			</Behavior>
			<Behavior Name="SitOnTheLeftEdgeOfIE" Frequency="50" />
			<Behavior Name="SitOnTheRightEdgeOfIE" Frequency="50" />
			<Behavior Name="JumpFromLeftEdgeOfIE" Frequency="0" />
			<Behavior Name="JumpFromRightEdgeOfIE" Frequency="0" />
			<Behavior Name="WalkLeftAlongIEAndSit" Frequency="0" />
			<Behavior Name="WalkRightAlongIEAndSit" Frequency="0" />
			<Behavior Name="WalkLeftAlongIEAndJump" Frequency="0" />
			<Behavior Name="WalkRightAlongIEAndJump" Frequency="0" />
		</Condition>

		<!-- On IE's Side -->
		<Condition Condition="#{mascot.lookRight ? mascot.environment.activeIE.leftBorder.isOn(mascot.anchor) :
					mascot.environment.activeIE.rightBorder.isOn(mascot.anchor)}">
			<Behavior Name="HoldOntoIEWall" Frequency="100" />
			<Behavior Name="ClimbIEWall" Frequency="100" />

		</Condition>

		<!-- On the Bottom of IE -->
		<Condition Condition="#{mascot.environment.activeIE.bottomBorder.isOn(mascot.anchor)}">
			<Behavior Name="ClimbIEBottom" Frequency="100" />
			<Behavior Name="GrabIEBottomLeftWall" Frequency="100" />
			<Behavior Name="GrabIEBottomRightWall" Frequency="100" />
		</Condition>

		<Behavior Name="JumpFromLeftWall" Frequency="0" Condition="#{!mascot.environment.workArea.leftBorder.isOn(mascot.anchor) &amp;&amp;
			mascot.anchor.x &lt; mascot.environment.workArea.left+400 &amp;&amp;
			Math.abs(mascot.environment.workArea.bottom-mascot.anchor.y) &lt;mascot.environment.workArea.height/4}" />
		<Behavior Name="JumpFromRightWall" Frequency="0" Condition="#{!mascot.environment.workArea.rightBorder.isOn(mascot.anchor) &amp;&amp;
			mascot.anchor.x &gt;= mascot.environment.workArea.right-400 &amp;&amp;
			Math.abs(mascot.environment.workArea.bottom-mascot.anchor.y) &lt;mascot.environment.workArea.height/4}" />

		<!-- IE Is Visible -->
		<Condition Condition="#{mascot.environment.activeIE.visible}">
			<Behavior Name="JumpOnIELeftWall" Frequency="0" Condition="#{mascot.anchor.x &lt; mascot.environment.activeIE.left &amp;&amp;
				Math.abs(mascot.environment.activeIE.bottom-mascot.anchor.y) &lt;mascot.environment.activeIE.height/4}" />
			<Behavior Name="JumpOnIERightWall" Frequency="0" Condition="#{mascot.anchor.x &gt; mascot.environment.activeIE.right &amp;&amp;
				Math.abs(mascot.environment.activeIE.bottom-mascot.anchor.y) &lt;mascot.environment.activeIE.height/4}" />

			<Behavior Name="ThrowIEFromLeft" Frequency="0" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &lt; mascot.environment.activeIE.left}" />
			<Behavior Name="ThrowIEFromRight" Frequency="0" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &gt; mascot.environment.activeIE.right}" />
			<Behavior Name="WalkAndThrowIEFromRight" Frequency="0" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &lt; mascot.environment.activeIE.left}" />
			<Behavior Name="WalkAndThrowIEFromLeft" Frequency="0" Condition="#{mascot.environment.activeIE.bottom &lt; mascot.anchor.y-64 &amp;&amp;
				mascot.anchor.x &gt; mascot.environment.activeIE.right}" />
		</Condition>


	</BehaviorList>
</Mascot>
